//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fittings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fittings.ProjectStrings", typeof(ProjectStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранный файл уже есть в списке прикреплений.
        ///Пожалуйста, выберите другой файл..
        /// </summary>
        internal static string ErrorEditAttachFileText {
            get {
                return ResourceManager.GetString("ErrorEditAttachFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка изменения файла.
        /// </summary>
        internal static string ErrorEditAttachFileTitle {
            get {
                return ResourceManager.GetString("ErrorEditAttachFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка заполнения данных.
        /// </summary>
        internal static string ErrorFillDataTitle {
            get {
                return ResourceManager.GetString("ErrorFillDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, заполните все поля со знаком (*)!.
        /// </summary>
        internal static string ErrorOfFillFields {
            get {
                return ResourceManager.GetString("ErrorOfFillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла ошибка при отправке:.
        /// </summary>
        internal static string ErrorSendMessageText {
            get {
                return ResourceManager.GetString("ErrorSendMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно отправить сообщение.
        /// </summary>
        internal static string ErrorSendMessageTitle {
            get {
                return ResourceManager.GetString("ErrorSendMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл успешно создан!.
        /// </summary>
        internal static string FileIsCreate {
            get {
                return ResourceManager.GetString("FileIsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт завершен!.
        /// </summary>
        internal static string ImportIsDone {
            get {
                return ResourceManager.GetString("ImportIsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спасибо, что используете нашу программу.
        ///Сообщение успешно отправлено разработчику!
        ///Через некоторое время Вам ответят..
        /// </summary>
        internal static string MessageSendedText {
            get {
                return ResourceManager.GetString("MessageSendedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение отправлено.
        /// </summary>
        internal static string MessageSendedTitle {
            get {
                return ResourceManager.GetString("MessageSendedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет данных для импорта.
        ///Пожалуйста, выберите файл с данными..
        /// </summary>
        internal static string NotDataForImport {
            get {
                return ResourceManager.GetString("NotDataForImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить портфель?.
        /// </summary>
        internal static string RemoveBriefcastText {
            get {
                return ResourceManager.GetString("RemoveBriefcastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление портфеля.
        /// </summary>
        internal static string RemoveBriefcastTitle {
            get {
                return ResourceManager.GetString("RemoveBriefcastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить группу?.
        /// </summary>
        internal static string RemoveComponentGroupText {
            get {
                return ResourceManager.GetString("RemoveComponentGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление группы фиттингов.
        /// </summary>
        internal static string RemoveComponentGroupTitle {
            get {
                return ResourceManager.GetString("RemoveComponentGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить оборудование?.
        /// </summary>
        internal static string RemoveEquipmentText {
            get {
                return ResourceManager.GetString("RemoveEquipmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление оборудования.
        /// </summary>
        internal static string RemoveEquipmentTitle {
            get {
                return ResourceManager.GetString("RemoveEquipmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить фиттинг?.
        /// </summary>
        internal static string RemoveFittingText {
            get {
                return ResourceManager.GetString("RemoveFittingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить проект?.
        /// </summary>
        internal static string RemoveProjectText {
            get {
                return ResourceManager.GetString("RemoveProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление.
        /// </summary>
        internal static string RemoveTitle {
            get {
                return ResourceManager.GetString("RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файл для импорта данных ....
        /// </summary>
        internal static string SelectFileForImportTitle {
            get {
                return ResourceManager.GetString("SelectFileForImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файл.
        /// </summary>
        internal static string SelectFileTitle {
            get {
                return ResourceManager.GetString("SelectFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите отправить сообщение разработчику?.
        /// </summary>
        internal static string SendMessageToDeveloperText {
            get {
                return ResourceManager.GetString("SendMessageToDeveloperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соглашение.
        /// </summary>
        internal static string SendMessageToDeveloperTitle {
            get {
                return ResourceManager.GetString("SendMessageToDeveloperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВНИМАНИЕ!
        ///В данной версии можно импортировать данные только из текстовых файлов..
        /// </summary>
        internal static string WarningImport {
            get {
                return ResourceManager.GetString("WarningImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        internal static string WarningImportTitle {
            get {
                return ResourceManager.GetString("WarningImportTitle", resourceCulture);
            }
        }
    }
}
